### ISSUE TITLE
Labs 5-6 assessment

### ISSUE THREAD

**Issue by grammarware** [jovanovski/uvasoftwaretesting15#5]
Week 5: nicely done, but why the sudden absolute lack of any kind of comments? Usually you were not that curt. I’m especially interested in Ex.2, since it involved a judgement call: what do you think of the result of the refactoring? Did it “improve the design of existing code”? Could you test the properties described in the assignment (extensibility, efficiency, etc)? How?

Week 6: you still use weird constructions like `do r <- testFermat k xs; return r`. Don’t give names to pets you do not intend to keep! Just `do testFermat k xs`.

Week 6: too bad the bonus doesn’t work with strings, that’s the kind of messages I usually send. Besides that, a nice framework, was very easy to test.

Week 5 is **+±** (bonus: yes; test reports: no), week 6 is **++**.

**Comment by mwijngaard** [comment]
@grammarware regarding to week 5 lack of comments & test reports: fair enough. I just wanted to give some personal feedback in that i enjoyed this weeks exercise the least as it basically just involved A LOT of copy-pasting and the code of the sudoku solver was really weird (eg. defining solving routines in 3 different places). To me it felt like this weeks exercise wasn't very well prepared. I think the intention should be to understand the concept of search trees, but it ends up being an exercise in understanding code written by somebody else. Anyways, maybe you want to do something with it for next year, maybe not, just my 2 cents :-).

**Comment by grammarware** [comment]
@mwijngaard thank you! Noted for future reference.

We usually had some exercise around sudoku because it is quite a sweet spot with still being a (solvable) puzzle and already not being solvable on a whim. It started with some blog post which has by now probably disappeared forever into 10+th page of google search, by someone who decided he could solve sudoku without any preparation in a much simpler way than anyone else — he failed, of course, and there was a thread of comments when people were posting counterexamples and the op was adding more and more patches for corner cases. If I remember correctly, two years ago we asked to implement it, last year to extend a given implementation to NRC and this year to refactor it. I've contemplated moving on to something cooler like [2048](https://gabrielecirulli.github.io/2048/), but it involves randomness and therefore harder to deal with.

In our defence I can say that in the future 80% of your time as a software engineer will be spent on maintenance and various attempts to understand someone else's code :innocent:

**Comment by mwijngaard** [comment]
Haha fair enough, but when I find one of my coworkers is defining the same
logic in 3 different places I tend to scold them for it... That's one of
the easiest causes of bugs when programming updates.

But It's not that I don't think sudokus are a good problem to solve, it's
just that the messiness of the implementation distracts from the actually
interesting parts of the exercise. I've never seen the 2048 problem before,
but it looks interesting! Maybe after the exams I'll give it a shot :-).

**Comment by grammarware** [comment]
One of the questions was “refactor this code” — nobody could stop you from refactoring it completely to your liking ;)
